os: linux
dist: trusty
cache: false
sudo: required
language: bash
services: docker
env:
  matrix:
  - ARCH=x86_64 PUID=1000 PGID=1000
  - ARCH=armhf PUID=1001 PGID=1001
  global:
  - secure: mLW+ojAWLn/j0ZTHUvrIHtPW9ypFwTrAFqzCiK3pjJD2nDp/PlDDeX8thYgSRBgjQJ4DvuX0F+NQr41e/CUH29pSckur6dajJodpF6IJhPlfWLA9Hv8y7dzJeH22UbZraaiuiNBtJjMZAGzeAAF6v64BoMybGXZ/2iqO5mTIOnafcBCTEqb8k6TkAl1WnypbX0JnwMHEMaWta78ltbCYuxiLLGYz9VUk8ZYYoaAIjw3Hobqz/qCABtvfpRwSl7lYofIUZN8iUvyLZIpvxZJ5ANCESwz0cpsGr9HGcW+4VxVYIhgWIGwCXDqoImgI+jiHf0TFDR4ViUEN2JODfrMR4reML9pzRAIhSSDJWiXTHkInDPjV9Kq3xo31wv/VsrwV0Stnr80sWfEXX5cR33KMqWQckQzhaEeMjJcsVONEbSRiWfhq+fxd2P+95X847b60Eb8FiQffS8jfqh/COcg63Of4+pJd7NSxnvMRcYY0K/eFAFJi22O0N5WZPzpLo9xJoE3TcLE2CL3KO/gyNUb0nswpt+QAmEIlUyRoNpZX/06Ig2SNPk1EoRp9ZwItF0kNcl3bJe7IAsx0HeZSVLyn83SUWse6bPIZlMyDPgpVbdPZjYmK08y9ZwA9M6InCkQv2N0LFCttT5za2X4487yPS3lpbH0uqs6Pd2miUeXHQF4=
  - secure: Q0PkMqtN21LN61OFme9EKr7k2FdupjFkhCBqOLEZiw3HTPO6G4R62zx0HT37QFTa6D/OJ4q/qinmD5uVpSHvAj2qbgdioONbKiQ+ejxk3k3NZmy5V3d+o+JBrvwtYEExNRagRybF5RVHPVFP3YnbjgME0M+5cGXXb1RdyVax5mnon2UQ2HxJ6ujAdBQ8rKV9wsOq1dJnyusiM9BsgLYIT6lC35H8PzW2Wr5HQDw0dBHbz4FvSQeluenoTmP3Vwkhn5FEgRDg9iMyRwKLQb17wgsvX8OtZ+4bYgd7DnA7wWdOc63XFLiHKodRRb9ML5m4zww5QXdOKnrZ6ef1B4peXeU4fWkSm8ETDaj03ova36cPiNhn4TNGtH6dBP/fO2+caGk0YXjUx0s4ClBJS0ecu3WHSeZW+WXVEzRynWqtdddbqsllJkKX5X8aZLvqtwyJQuPDsqqZYNAbWfKkfp35GjY5wMap7uysvhzCOxIxFPbgs0b0+00M5FcDPqOx0WzkShsZ33YJPoZorAQgbM87u01A+k2Adta5Ua8jAe2TxOVE7l1eZnzh9+AubWA0EK7js5lhLhNjLNNAlrGzeBMnnsepA36WuueC+CIdRJwWzDNwaR0qC/jIReFnb5mmrTV6NMFRajfcj6m4iCxlSqFua8L7XUK9GiowpMi9qFZ0YGs=
install: true
before_script:
- docker --version
- make --version
script:
- make ARCH=${ARCH} PUID=${PUID} PGID=${PGID} build test
after_success:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- make ARCH=${ARCH} push
after_script:
- docker logout
- make clean
